WoodScape Tutorial version 0
debiai/docs pull request #24
Opened 2023-12-05 16:30 UTC by SabrinaChaouche

2023-12-05 16:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/debiai/docs?pullRequest=24) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/debiai/docs?pullRequest=24) before we can accept your contribution.<br/><hr/>**sabrina.chaouche** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/debiai/docs?pullRequest=24) it.</sub>

2023-12-05 16:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/debiai/docs?pullRequest=24) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/debiai/docs?pullRequest=24) before we can accept your contribution.<br/><hr/>**sabrina.chaouche** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/debiai/docs?pullRequest=24) it.</sub>

2023-12-11 16:01 UTC, Tomansion requested changes

2023-12-11 16:01 UTC, Tomansion commented on documentation/useCases/WoodScape_Tutorial/README.md
> +In this case study, we used approximately *72K images* and focused on the 2D bounding boxes detection task with five classes: *vehicle, person, bicycle, traffic light and traffic sign.*
![image](https://github.com/debiai/docs/assets/59999324/7d9fc2c7-663f-4d8d-acc2-89308732b159)
72k images or objects ?

2023-12-11 16:01 UTC, Tomansion commented on documentation/useCases/WoodScape_Tutorial/README.md
> +To further investigates the dataset, we explore the distribution of each one of the train, validation and test sets using the **“Data Distribution”** widget.
Nothing to learn from the two images ?

2023-12-11 16:01 UTC, Tomansion commented on documentation/useCases/WoodScape_Tutorial/README.md
> +![Parallel Coordinates 02](./images/02_Parallel_Coordinates.png)
I suggest that you move the images on top of the comments (just bellow the line n°26 or 28

2023-12-11 16:01 UTC, Tomansion commented on documentation/useCases/WoodScape_Tutorial/README.md
> +The [Figure 3](#figure-03---woodscape-dataset-split-from-left-to-train-train-validation-and-test-by-objects-class-distribution-grouped-by-camera-id) displays the distribution of each of the three set
I suggest that you put the interpretation of the results bellow the image

2023-12-11 16:01 UTC, Tomansion commented on documentation/useCases/WoodScape_Tutorial/README.md
> +The [Figure 3](#figure-03---woodscape-dataset-split-from-left-to-train-train-validation-and-test-by-objects-class-distribution-grouped-by-camera-id) displays the distribution of each of the three set
Same suggestions for the next interpretations

2023-12-11 16:01 UTC, Tomansion commented on documentation/useCases/WoodScape_Tutorial/README.md
> +The WoodScape dataset is a public dataset containing more than *100K
Please add a link to the Woodscape dataset

2023-12-11 16:01 UTC, Tomansion commented on documentation/useCases/WoodScape_Tutorial/README.md
> +2. Analysing the models results.
1. Please make those links to the different sections

2. Have you planned to do a `0. Inserting the project Data into DebiAI` step by step guide ?
    If yes, please create a second page with your documented python code or notebook (use a notebook to markdown tool). Then add in this page a link to your new page.

2023-12-11 16:01 UTC, Tomansion commented on documentation/useCases/WoodScape_Tutorial/README.md
> +![Data Distribution 03](./images/03_Data_Distribution.png)
I think that a step by step explanation of how to recreate this is required in this tutorial.

2023-12-11 16:01 UTC, Tomansion commented on documentation/useCases/WoodScape_Tutorial/README.md
> +We used two versions of YOLO-based
Please add a link to learn more about Yolo

2023-12-11 16:01 UTC, Tomansion commented on documentation/useCases/WoodScape_Tutorial/README.md
> +The [Figure 4](#figure-05-the-relationship-between-the-precision-and-recall-for-each-model-using-the-night-stars-plot-widget) shows that the two models trained on the WoodScape's train set have bette
We don't see the X axis

2023-12-11 16:01 UTC, Tomansion commented on documentation/useCases/WoodScape_Tutorial/README.md
> +![Point Plot 07](./images/08_Point_Plot_f1-score_nb-vehicles_vs_f1-score_nb_persons.png)
I find the plot with the number of bike better in terms of model comparaison.
![image](https://github.com/debiai/docs/assets/59999324/64eb0929-0578-4d61-a55d-10bf1308021f)

Moreover, bikes is a known challenge for Valeo

2023-12-13 21:10 UTC, SabrinaChaouche commented on documentation/useCases/WoodScape_Tutorial/README.md
> +2. Analysing the models results.
Reply to 2: this has been postponed.

2023-12-15 14:23 UTC, SabrinaChaouche commented on documentation/useCases/WoodScape_Tutorial/README.md
> +The [Figure 4](#figure-05-the-relationship-between-the-precision-and-recall-for-each-model-using-the-night-stars-plot-widget) shows that the two models trained on the WoodScape's train set have bette
A problem to resolve on DebiAI!

2024-01-24 10:16 UTC, Tomansion approved these changes

2024-01-24 10:16 UTC, Tomansion commented on documentation/useCases/WoodScape_Tutorial/README.md
> +2. Analysing the models results in the project *WoodScape - Images*. [See here](#results-analysis)
The two links don't work

2024-03-27 18:02 UTC, merged